### ISSUE TITLE
I do not understand.

### ISSUE THREAD

**Issue by ZoltXs** [YinHangCode/homebridge-mi-philips-light#15]
All the correct code and the homebridge runs without problems and I can not see any light bulb.

"platforms": [{
						"platform": "MiPhilipsLightPlatform",
						"deviceCfgs": [{
							"type": "SmartBulb",
							"ip": "192.168.0.162",
							"token": "24960cb3fdccc30a56a617cb931c4b7a",
							"lightName": "lampara tv 1",
							"lightDisable": false
						}, 
							{
							"type": "SmartBulb",
							"ip": "192.168.0.161",
							"token": "4ca64368d2b25193c3f3b42d5129e3c8",
							"lightName": "lampara tv 2",
							"lightDisable": false
						}, {
							"type": "SmartBulb",
							"ip": "192.168.0.166",
							"token":"f8e3a6e3dd0e09684a30528b8d4a685c",
							"lightName": "Lamparilla",
							"lightDisable": false
						}]
					}]
				}
			}
		}
	}]
}

**Comment by YinHangCode** [comment]
It seems that there is a "}]" of superfluous.
```
    "platforms": [{
        "platform": "MiPhilipsLightPlatform",
        "deviceCfgs": [{
            "type": "SmartBulb",
            "ip": "192.168.0.162",
            "token": "24960cb3fdccc30a56a617cb931c4b7a",
            "lightName": "lampara tv 1",
            "lightDisable": false
        }, {
            "type": "SmartBulb",
            "ip": "192.168.0.161",
            "token": "4ca64368d2b25193c3f3b42d5129e3c8",
            "lightName": "lampara tv 2",
            "lightDisable": false
        }, {
            "type": "SmartBulb",
            "ip": "192.168.0.166",
            "token": "f8e3a6e3dd0e09684a30528b8d4a685c",
            "lightName": "Lamparilla",
            "lightDisable": false
        }]
    }]
```

**Comment by ZoltXs** [comment]
I enter your correct code but I still do not see,

{
	"bridge": {
		"name": "MiHome",
		"username": "CC:22:3D:E3:EC:29",
		"port": 51881,
		"pin": "031-45-154"
	},
	"description": "My House",
	"accessories": [{
		"accessory": "NefitEasy",
		"name": "termostato",
		"options": {
			"serialNumber": "660980988",
			"accessKey": "KTLVBPB32Pc3v***",
			"password": "****"
		}
	}],
    "platforms": [{
        "platform": "MiPhilipsLightPlatform",
        "deviceCfgs": [{
            "type": "SmartBulb",
            "ip": "192.168.0.162",
            "token": "24960cb3fdccc30a56a617cb931c4b7a",
            "lightName": "lampara tv 1",
            "lightDisable": false
        }, {
            "type": "SmartBulb",
            "ip": "192.168.0.161",
            "token": "4ca64368d2b25193c3f3b42d5129e3c8",
            "lightName": "lampara tv 2",
            "lightDisable": false
        }, {
            "type": "SmartBulb",
            "ip": "192.168.0.166",
            "token": "f8e3a6e3dd0e09684a30528b8d4a685c",
            "lightName": "Lamparilla",
            "lightDisable": false
        }]
    }]
}

**Comment by ZoltXs** [comment]
Solved, you are the best, thank you
