### ISSUE TITLE
This plugin slows down Homebridge

### ISSUE THREAD

**Issue by louliangsheng** [YinHangCode/homebridge-mi-philips-light#47]
[homebridge-mi-philips-light] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

via:homebridge 13.4  Node.js v14.17.1    Npm v7.17.0

**Comment by avielc** [comment]
Did you find a solution?
