### ISSUE TITLE
请问大神可以homebridge-mi-aqara和homebridge-mi-philips-light一起用吗？

### ISSUE THREAD

**Issue by Jiahui-Bai** [YinHangCode/homebridge-mi-philips-light#6]
请问大神有什么办法可以在一台树莓派上让您的homebridge-mi-aqara和homebridge-mi-philips-light两个一起运行？我看两个运行命令好像都是homebridge，不知道怎么办了。

**Comment by YinHangCode** [comment]
都加到配置里
或者开两个hb

**Comment by HueyBai** [comment]
大神，我是小白，请您详解，您说的开两个hb，是不是两个全安装，配置是不是各配置各的，可是运行的命令一样啊，怎么分别运行他们呢？

**Comment by YinHangCode** [comment]
通过-U和-P参数分别指向不同的配置文件，群里有多开教程 你可以看一下

**Comment by HueyBai** [comment]
大神我没有加群，请问我可以加这个群吗？要是可以的话能不能发一下群号，谢谢🙏

**Comment by YinHangCode** [comment]
说明里就有群号，QQ Group: 107927710.

**Comment by HueyBai** [comment]
谢谢🙏
